// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FilterKey int32

const (
	FilterKey_Action    FilterKey = 0
	FilterKey_ActorType FilterKey = 1
	FilterKey_ActorID   FilterKey = 2
	FilterKey_NodeID    FilterKey = 3
	FilterKey_ServiceID FilterKey = 4
)

var FilterKey_name = map[int32]string{
	0: "Action",
	1: "ActorType",
	2: "ActorID",
	3: "NodeID",
	4: "ServiceID",
}
var FilterKey_value = map[string]int32{
	"Action":    0,
	"ActorType": 1,
	"ActorID":   2,
	"NodeID":    3,
	"ServiceID": 4,
}

func (x FilterKey) String() string {
	return proto.EnumName(FilterKey_name, int32(x))
}
func (FilterKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type StateValue int32

const (
	StateValue_Undefined   StateValue = 0
	StateValue_Activated   StateValue = 1
	StateValue_Deactivated StateValue = 2
)

var StateValue_name = map[int32]string{
	0: "Undefined",
	1: "Activated",
	2: "Deactivated",
}
var StateValue_value = map[string]int32{
	"Undefined":   0,
	"Activated":   1,
	"Deactivated": 2,
}

func (x StateValue) String() string {
	return proto.EnumName(StateValue_name, int32(x))
}
func (StateValue) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type EventActorType int32

const (
	EventActorType_node    EventActorType = 0
	EventActorType_service EventActorType = 1
	EventActorType_state   EventActorType = 2
)

var EventActorType_name = map[int32]string{
	0: "node",
	1: "service",
	2: "state",
}
var EventActorType_value = map[string]int32{
	"node":    0,
	"service": 1,
	"state":   2,
}

func (x EventActorType) String() string {
	return proto.EnumName(EventActorType_name, int32(x))
}
func (EventActorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type EventAction int32

const (
	EventAction_created EventAction = 0
	EventAction_updated EventAction = 1
	EventAction_deleted EventAction = 2
)

var EventAction_name = map[int32]string{
	0: "created",
	1: "updated",
	2: "deleted",
}
var EventAction_value = map[string]int32{
	"created": 0,
	"updated": 1,
	"deleted": 2,
}

func (x EventAction) String() string {
	return proto.EnumName(EventAction_name, int32(x))
}
func (EventAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type Filters struct {
	// Key value is from the FilterKey enum.
	// TODO: change to string keys
	Args map[int32]string `protobuf:"bytes,1,rep,name=Args,json=args" json:"Args,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Filters) Reset()                    { *m = Filters{} }
func (m *Filters) String() string            { return proto.CompactTextString(m) }
func (*Filters) ProtoMessage()               {}
func (*Filters) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Filters) GetArgs() map[int32]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type Node struct {
	// TODO: rename fields with plugin
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Node) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Service struct {
	ID   string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Service) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type State struct {
	Value   StateValue `protobuf:"varint,1,opt,name=Value,json=value,enum=api.StateValue" json:"Value,omitempty"`
	Until   int64      `protobuf:"varint,2,opt,name=Until,json=until" json:"Until,omitempty"`
	Service *Service   `protobuf:"bytes,3,opt,name=Service,json=service" json:"Service,omitempty"`
	Node    *Node      `protobuf:"bytes,4,opt,name=Node,json=node" json:"Node,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *State) GetValue() StateValue {
	if m != nil {
		return m.Value
	}
	return StateValue_Undefined
}

func (m *State) GetUntil() int64 {
	if m != nil {
		return m.Until
	}
	return 0
}

func (m *State) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *State) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type Event struct {
	ID        string         `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Action    EventAction    `protobuf:"varint,2,opt,name=Action,json=action,enum=api.EventAction" json:"Action,omitempty"`
	ActorID   string         `protobuf:"bytes,3,opt,name=ActorID,json=actorID" json:"ActorID,omitempty"`
	ActorType EventActorType `protobuf:"varint,4,opt,name=ActorType,json=actorType,enum=api.EventActorType" json:"ActorType,omitempty"`
	// Types that are valid to be assigned to Actor:
	//	*Event_Node
	//	*Event_Service
	//	*Event_State
	Actor isEvent_Actor `protobuf_oneof:"Actor"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type isEvent_Actor interface {
	isEvent_Actor()
}

type Event_Node struct {
	Node *Node `protobuf:"bytes,5,opt,name=Node,json=node,oneof"`
}
type Event_Service struct {
	Service *Service `protobuf:"bytes,6,opt,name=Service,json=service,oneof"`
}
type Event_State struct {
	State *State `protobuf:"bytes,7,opt,name=State,json=state,oneof"`
}

func (*Event_Node) isEvent_Actor()    {}
func (*Event_Service) isEvent_Actor() {}
func (*Event_State) isEvent_Actor()   {}

func (m *Event) GetActor() isEvent_Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetAction() EventAction {
	if m != nil {
		return m.Action
	}
	return EventAction_created
}

func (m *Event) GetActorID() string {
	if m != nil {
		return m.ActorID
	}
	return ""
}

func (m *Event) GetActorType() EventActorType {
	if m != nil {
		return m.ActorType
	}
	return EventActorType_node
}

func (m *Event) GetNode() *Node {
	if x, ok := m.GetActor().(*Event_Node); ok {
		return x.Node
	}
	return nil
}

func (m *Event) GetService() *Service {
	if x, ok := m.GetActor().(*Event_Service); ok {
		return x.Service
	}
	return nil
}

func (m *Event) GetState() *State {
	if x, ok := m.GetActor().(*Event_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_Node)(nil),
		(*Event_Service)(nil),
		(*Event_State)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// Actor
	switch x := m.Actor.(type) {
	case *Event_Node:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Node); err != nil {
			return err
		}
	case *Event_Service:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Service); err != nil {
			return err
		}
	case *Event_State:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.State); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Actor has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 5: // Actor.Node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Node)
		err := b.DecodeMessage(msg)
		m.Actor = &Event_Node{msg}
		return true, err
	case 6: // Actor.Service
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Service)
		err := b.DecodeMessage(msg)
		m.Actor = &Event_Service{msg}
		return true, err
	case 7: // Actor.State
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(State)
		err := b.DecodeMessage(msg)
		m.Actor = &Event_State{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// Actor
	switch x := m.Actor.(type) {
	case *Event_Node:
		s := proto.Size(x.Node)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Service:
		s := proto.Size(x.Service)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_State:
		s := proto.Size(x.State)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Filters)(nil), "api.Filters")
	proto.RegisterType((*Node)(nil), "api.Node")
	proto.RegisterType((*Service)(nil), "api.Service")
	proto.RegisterType((*State)(nil), "api.State")
	proto.RegisterType((*Event)(nil), "api.Event")
	proto.RegisterEnum("api.FilterKey", FilterKey_name, FilterKey_value)
	proto.RegisterEnum("api.StateValue", StateValue_name, StateValue_value)
	proto.RegisterEnum("api.EventActorType", EventActorType_name, EventActorType_value)
	proto.RegisterEnum("api.EventAction", EventAction_name, EventAction_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x93, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0xf9, 0xd1, 0x98, 0x89, 0xe6, 0x96, 0x55, 0x8e, 0x20, 0x88, 0x25, 0xa0, 0x84,
	0x80, 0x05, 0xa3, 0xa0, 0xe8, 0x53, 0x25, 0x27, 0x2d, 0x42, 0x1f, 0xf6, 0x3c, 0xdf, 0xd7, 0x66,
	0x3d, 0x82, 0xbd, 0x24, 0x24, 0xdb, 0x42, 0xfe, 0x01, 0x5f, 0xfc, 0xa7, 0x65, 0x67, 0xd3, 0xf4,
	0xce, 0x3e, 0x75, 0x77, 0xe6, 0x3b, 0x33, 0x9f, 0xef, 0x6c, 0x03, 0xa1, 0x1a, 0x5a, 0xd9, 0x2f,
	0xda, 0xae, 0x51, 0x0d, 0x73, 0x44, 0x5b, 0x25, 0x35, 0xf8, 0x5f, 0xab, 0x9d, 0x92, 0x5d, 0xcf,
	0x32, 0x70, 0x97, 0xdd, 0x6d, 0x1f, 0x93, 0xb9, 0x93, 0x86, 0xf9, 0xe5, 0x42, 0xb4, 0xd5, 0x62,
	0xcc, 0x2d, 0x74, 0xe2, 0xaa, 0x56, 0xdd, 0xc0, 0x5d, 0xd1, 0xdd, 0xf6, 0xcf, 0x3f, 0x40, 0x30,
	0x85, 0x18, 0x05, 0xe7, 0xb7, 0x1c, 0x62, 0x32, 0x27, 0xa9, 0xc7, 0xf5, 0x91, 0x3d, 0x03, 0xef,
	0x20, 0x76, 0x7b, 0x19, 0xdb, 0x73, 0x92, 0x06, 0xdc, 0x5c, 0x3e, 0xd9, 0x1f, 0x49, 0x72, 0x09,
	0xee, 0xa6, 0x29, 0x25, 0x8b, 0xc0, 0x5e, 0x17, 0x58, 0x12, 0x70, 0xbb, 0x2a, 0x92, 0x37, 0xe0,
	0x5f, 0xcb, 0xee, 0x50, 0x6d, 0xcf, 0x52, 0x8c, 0x81, 0xbb, 0x11, 0x77, 0xc7, 0x5e, 0x6e, 0x2d,
	0xee, 0x64, 0xf2, 0x97, 0x80, 0x77, 0xad, 0x84, 0x92, 0xec, 0x15, 0x78, 0x3f, 0x70, 0x94, 0x2e,
	0x88, 0xf2, 0x0b, 0xc4, 0xc6, 0x14, 0x86, 0xc7, 0xd9, 0x9a, 0xe8, 0xa6, 0x56, 0xd5, 0x0e, 0xbb,
	0x38, 0xdc, 0xdb, 0xeb, 0x0b, 0x7b, 0x3d, 0x4d, 0x8d, 0x9d, 0x39, 0x49, 0xc3, 0xfc, 0xb1, 0x29,
	0x37, 0x31, 0xee, 0xf7, 0x23, 0xd2, 0x0b, 0x43, 0x1d, 0xbb, 0x28, 0x0a, 0x50, 0xa4, 0x03, 0xdc,
	0xad, 0x9b, 0x52, 0x26, 0x7f, 0x6c, 0xf0, 0xae, 0x0e, 0xb2, 0x56, 0x67, 0xec, 0x29, 0xcc, 0x96,
	0x5b, 0x55, 0x35, 0x35, 0xce, 0x8d, 0x72, 0x8a, 0xa5, 0xa8, 0x35, 0x71, 0x3e, 0x13, 0xf8, 0xcb,
	0x62, 0xf0, 0x97, 0x5b, 0xd5, 0x74, 0xeb, 0x02, 0x51, 0x02, 0xee, 0x0b, 0x73, 0x65, 0x6f, 0x21,
	0xc0, 0xcc, 0xf7, 0xa1, 0x35, 0x04, 0x51, 0xfe, 0xf4, 0x41, 0x1b, 0x93, 0xe2, 0x81, 0x38, 0x1e,
	0xd9, 0xcb, 0x91, 0xd7, 0xfb, 0x8f, 0x77, 0x65, 0x19, 0x62, 0x96, 0x9e, 0x8c, 0xcf, 0xce, 0x8d,
	0xaf, 0xac, 0x93, 0xf5, 0x64, 0x5c, 0x74, 0xec, 0xa3, 0x0e, 0x4e, 0xfb, 0x5d, 0x59, 0xdc, 0xeb,
	0xf5, 0xe1, 0x8b, 0x0f, 0x1e, 0x62, 0x64, 0x1b, 0x08, 0xcc, 0x3f, 0xe6, 0x9b, 0x1c, 0x18, 0x1c,
	0xbd, 0x53, 0x8b, 0x3d, 0xb9, 0xe7, 0x81, 0x12, 0x16, 0x4e, 0x66, 0xa9, 0xad, 0x75, 0x9a, 0x6d,
	0x5d, 0x50, 0x47, 0xeb, 0x46, 0x86, 0x75, 0x41, 0xdd, 0xec, 0x33, 0xc0, 0xe9, 0x29, 0x75, 0xf2,
	0xa6, 0x2e, 0xe5, 0xaf, 0xaa, 0x96, 0xe5, 0xd4, 0xb3, 0x3a, 0x08, 0x25, 0x4b, 0x4a, 0xd8, 0x05,
	0x84, 0x85, 0x14, 0x53, 0xc0, 0xce, 0x72, 0x88, 0x1e, 0x6e, 0x88, 0x3d, 0x02, 0x74, 0x4f, 0x2d,
	0x0d, 0x30, 0x1a, 0xa4, 0x84, 0x05, 0x60, 0x7c, 0x50, 0x3b, 0x7b, 0x0f, 0xe1, 0xbd, 0xc7, 0xd1,
	0xb2, 0x6d, 0x27, 0xb1, 0x1f, 0xd6, 0xec, 0xdb, 0x72, 0x9c, 0x16, 0x82, 0x5f, 0xca, 0x9d, 0xc4,
	0x49, 0x3f, 0x67, 0xf8, 0x41, 0xbd, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x84, 0x3e, 0x8a,
	0x5f, 0x03, 0x00, 0x00,
}
